# ***NUMPY***

1) **Creating** **Numpy** **Array**

In [39]:
# np.array
import numpy as np

a = np.array([1,2,3])
a

array([1, 2, 3])

In [40]:
# 2D
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
# 3D
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [42]:
# dtype
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [43]:
np.arange(1,11) # (start to n-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
np.arange(1,11,3) # third value is the jump number that print after the number

array([ 1,  4,  7, 10])

In [45]:
# 3D
np.arange(16).reshape(2,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [46]:
np.arange(32).reshape(8,2,2) # it has 8 rows, each containing 2 matrices of 2 elements each.

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31]]])

In [47]:
# with reshape
# 4D
np.arange(16).reshape(2,2,2,2) # product of reshape values must be equal to array number

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [48]:
# 4D
np.arange(32).reshape(4,2,2,2) # it has 4 blocks, each consisting of 2 rows and 2 matrices of 2 elements each.

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]],


       [[[24, 25],
         [26, 27]],

        [[28, 29],
         [30, 31]]]])

In [49]:
# zeros matrix
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [50]:
#ones matrix
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [51]:
# random matrix
np.random.random((3,4)) # by default generated value 0 to 1

array([[0.23252876, 0.39192945, 0.98802309, 0.94706425],
       [0.45771173, 0.92314656, 0.42265465, 0.25030585],
       [0.15954216, 0.42118921, 0.89156104, 0.5884773 ]])

In [52]:
import numpy as np

# Generate a random integer between 1 and 10
random_integer = np.random.randint(1, 11)
print(random_integer,'\n')

# Generate a 3x3 array of random integers between 0 and 100
random_array = np.random.randint(0, 101, size=(3, 3))
print(random_array)


3 

[[53 85 62]
 [30 11  1]
 [53 54 89]]


In [53]:
# Linspace
np.linspace(-10,10,9) # equal difference of 9 values between -10 to 10

array([-10. ,  -7.5,  -5. ,  -2.5,   0. ,   2.5,   5. ,   7.5,  10. ])

In [54]:
np.linspace(-10,10,9, dtype=int)

array([-10,  -8,  -5,  -3,   0,   2,   5,   7,  10])

In [55]:
# Identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

2)  **Array Attributers**

In [56]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [57]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [58]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [59]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [60]:
# Dimentions
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [61]:
# Shape
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [62]:
# Size
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [63]:
# Itemsize
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
8


In [64]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


In [65]:
# CHANGING DATADYPE
# astype
a3.astype(np.int32)
print(a3.dtype)

int64


3)  **Array operations**

In [66]:
b1 = np.arange(12).reshape(3,4)
b2 = np.arange(12,24).reshape(3,4)
print(b1,'\n')
print(b2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


3i) *Scalar operations*

In [67]:
# Arithmetic
b1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [68]:
# Relational
b2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

3ii) *Vector operations*

In [69]:
# Arithmetic
b1 ** b2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

4)  **Array Function**

In [70]:
c1 = np.random.random((3,4))
c1 = np.round(c1 * 100)
c1

array([[40., 41., 56.,  5.],
       [13., 80., 64., 59.],
       [30., 58., 91., 53.]])

In [84]:
# Min
print("Min :",np.min(c1))

# Max
print("Max :",np.max(c1))

# Sum
print("Sum :",np.sum(c1))

# product
print("product :",np.product(c1))

Min : 5.0
Max : 91.0
Sum : 590.0
product : 1.513330254299136e+19


In [86]:
# 0 --> Col and 1 --> Row
print("Min in every col :", np.min(c1, axis=0))
print("Min in every row :", np.min(c1, axis=1))
print("product of every col :",np.product(c1, axis=0))

Min in every col : [13. 41. 56.  5.]
Min in every row : [ 5. 13. 30.]
product of every col : [ 15600. 190240. 326144.  15635.]


In [87]:
# Mean /Median /std /var

In [100]:
# Dot product
d1 = np.arange(12).reshape(3,4)
d2 = np.arange(12,24).reshape(4,3)
print(d1,'\n\n',d2)

# matrix 1 col and matrix 2 row must be equal

print('\n',np.dot(d1,d2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

 [[114 120 126]
 [378 400 422]
 [642 680 718]]


In [93]:
# log and exponent

In [94]:
a1 = 55.4

In [99]:
# Round /floor /ceil

print(np.round(a1))
print(np.floor(a1))
print(np.ceil(a1))

55.0
55.0
56.0


 5) **Indexing**

In [103]:
z1 = np.arange(10)
z2 = np.arange(12).reshape(3,4)
z3 = np.arange(8).reshape(2,2,2)
print(z1,'\n\n')
print(z2,'\n\n')
print(z3,'\n\n')

[0 1 2 3 4 5 6 7 8 9] 


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] 




In [113]:
# 0 is first index and -1 is last index
print(z1[0])
print(z1[-1])

0
9


In [114]:
z2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [119]:
# for value 6 first we need to write row of value 6 (1) than col of value 6 (2)
z2[1,2]

6

In [126]:
z3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [127]:
# 3D is the combination of 2Ds
# In 3D matrix first we give matrix number than row and col like 2D
#like if we need to find 4

z3[1,0,0] # 1 means 2nd matrix of 3D matrix, 0 means 1st row of 2nd matrix, 2nd 0 means 1st col of 2nd matrix

4

In [128]:
z3[0,1,1]

3

6) **Slicing**

In [122]:
z1[2:5]

array([2, 3, 4])

In [131]:
z2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [133]:
z2[0,:] # for 1st row

array([0, 1, 2, 3])

In [134]:
z2[:,2] # for 2nd col

array([ 2,  6, 10])

In [130]:
z2[0:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [138]:
z2[1:3,1:3] # its also gives the same output z2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [148]:
z2[::2,::3]
#z2[0::2,0::3]

array([[ 0,  3],
       [ 8, 11]])

In [158]:
#z2[0::2,1::2]
z2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [159]:
z2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [162]:
z2[1,0::3]

array([4, 7])

In [167]:
z2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [169]:
z3 = np.arange(27).reshape(3,3,3)
z3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [177]:
z3[1] # for 2nd array of 3D

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [178]:
z3[0::2] # for 1st and 3rd array of 3D

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [179]:
z3[0,1] # for 2nd row of 1st array od 3D

array([3, 4, 5])

In [180]:
z3[1,:,1] # for middle col of 2nd array of 3D

array([10, 13, 16])

In [187]:
z3[2,1:,1:]
#z3[2,1:3,1:3]

array([[22, 23],
       [25, 26]])

In [188]:
z3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [199]:
# for 0,2,18,20
z3[0::2,0,0::2]
# z3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

7) **Iterating**

In [209]:
print(z1,'\n')

for i in z1:
  print(i)

[0 1 2 3 4 5 6 7 8 9] 

0
1
2
3
4
5
6
7
8
9


In [210]:
print(z2,'\n')

for i in z2:
  print(i,'\n') # In 2D a row print in 1 time

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[0 1 2 3] 

[4 5 6 7] 

[ 8  9 10 11] 



In [211]:
print(z3,'\n')

for i in z3:
  print(i,'\n') # In 3D a 2D printed in 1 time

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] 

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[ 9 10 11]
 [12 13 14]
 [15 16 17]] 

[[18 19 20]
 [21 22 23]
 [24 25 26]] 



In [213]:
# To print every single item in 2D,3D etc we use nditer(convert array in 1D than print)
for i in np.nditer(z3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


8) **Reshaping**

In [214]:
#reshape

In [219]:
#Transpose
print(z2)

print('\n',np.transpose(z2))
# print('\n',z2.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [220]:
# ravel(convert array in 1D)
z2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [221]:
z3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

9) **Stacking**

In [223]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
print(a4,'\n')
print(a5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [228]:
# Horizontal stacking
np.hstack((a4,a5)) # shape must be same

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [229]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

10) **Spliting**

In [234]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [235]:
# Horizontal spliting
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [237]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [240]:
# Vertical spliting
np.vsplit(a5,3)


[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]